sudo: required
services:
    - docker

before_install:
    - docker build -t mskdocker92/docker-react -f Dockerfile.dev .

script:
    - docker run mskdocker92/docker-react npm run test -- --coverage

deploy:
    provide: elasticbeanstalk
    region: "us-east-1"
    app: "docker-react" #aws app
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-532585711156"
    bucket_path: "docker-react" #same as app name
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"